import frappe
from frappe.desk.doctype.kanban_board.kanban_board import add_column

def create_kanban():
    boards = [
        {
            "name": "Finance Approvals",
            "doctype": "Outgoing Document"
        },
        {
            "name": "Procurement Approvals",
            "doctype": "Outgoing Document"
        },
        {
            "name": "Engineering Approvals",
            "doctype": "Outgoing Document"
        },
        {
            "name": "HR Approvals",
            "doctype": "Internal Document"
        }
    ]
    
    for b in boards:
        if frappe.db.exists("Kanban Board", b["name"]):
            frappe.delete_doc("Kanban Board", b["name"], force=True)
            
        doc = frappe.new_doc("Kanban Board")
        doc.kanban_board_name = b["name"]
        doc.reference_doctype = b["doctype"]
        doc.field_name = "status"
        doc.private = 0
        doc.fields = '["name","subject","category","status","document_date"]'
        
        # We explicitly DO NOT set doc.filters here. 
        # Frappe Kanbans fight with the URL parameters generated by Workspaces when both are set.
        
        doc.insert(ignore_permissions=True)

        # Safely add columns using Frappe's own API
        add_column(b["name"], "Draft")
        add_column(b["name"], "Pending")
        add_column(b["name"], "Approved")
        
        if b["doctype"] == "Outgoing Document":
            add_column(b["name"], "Dispatched")
            
        add_column(b["name"], "Cancelled")

        print(f"Kanban Board '{b['name']}' built via API (Without conflicting internal filters).")

if __name__ == "__main__":
    create_kanban()
